create table game (
  id int generated by default as identity (start with 42) primary key,
  nickname varchar(32) unique not null,
  title varchar(64) not null,
  active boolean default false not null
);

create table status (
  id tinyint primary key,
  title varchar(16) not null,
  finalized boolean default true not null
);

create table matches (
  id int identity primary key,
  game_id int not null,
  title varchar(64) not null,
  status_id tinyint default 0 not null,
  foreign key (game_id) references game (id),
  foreign key (status_id) references status (id)
);

create table moves (
  id int generated by default as identity primary key,
  match_id int not null,
  opponent char not null,
  position tinyint not null,
  performed timestamp default current_timestamp,
  foreign key (match_id) references matches (id),
  check (opponent='X' or opponent='O'),
  check (position>=0 and position<=8)
)
